name: Build redoc
on:
  schedule:
   - cron: '0 * * * 1-5'
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: npm ci
    - name: Build docs
      run: npm run build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3 # https://github.com/peaceiris/actions-gh-pages
      with:
        deploy_key: ${{ secrets.DEPLOY_KEY }}
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        publish_dir: ./public
        force_orphan: true
        exclude_assets: '.github,openapi,.redocly.yaml,LICENSE,README.md'
        cname: api-docs.c1st.com
